# version: "3.9"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: web_db
      POSTGRES_USER: web_usr
      POSTGRES_PASSWORD: p@ssw0rd
  web:
    image: nginx:latest
    volumes:
      - ./conf:/etc/nginx
      - ./static:/app/static
    ports:
      - "80:80"
    depends_on:
      - db
